---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-with-volume
spec:
 containers: 
  - name: alpine-container-with-volume
    image: alpine
    args:
     - /bin/sh
     - -c
     - sleep 1d
    volumeMounts:
     - name: logs-volume
       mountPath: /tmp/logs
 volumes:
  - name: logs-volume
    emptyDir: {}
        