---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-with-cmap
spec:
 containers:
  - name: alpine
    image: alpine
    args:
     - /bin/sh
     - -c
     - sleep 1d
    envFrom:
     - configMapRef:
        name: learning-cmap