--- 
apiVersion: v1
kind: Pod
metadata:
 name: secret-demo
 labels:
  app: alpine
  team: devops
spec:
 containers:
  - name: alpine-container
    image: alpine
    args:
     - /bin/sh
     - -c
     - sleep 1d
    envFrom:
     - secretRef:
        name: app-secret