--- 
apiVersion: v1
kind: Pod
metadata:
 name: httpd-pod-with-emptydir-volume
 labels:
  app: httpd
  team: devops
spec:
 containers:
  - name: alpine-container
    image: alpine
    args:
     - /bin/sh
     - -c
     - sleep 1d
    volumeMounts:
     - mountPath: /var/log
       name: httpd-logs-mount
 volumes: 
  - name: httpd-logs-mount
    emptyDir: {}