--- 
apiVersion: v1
kind: Pod
metadata:
 name: httpd-pod
 labels:
  app: httpd
  team: devops
spec:
 containers:
  - name: httpd-container
    image: httpd:latest
    ports:
     - containerPort: 80
       protocol: TCP
    volumeMounts:
     - mountPath: /logs
       name: httpd-mount
 volumes: 
  - name: httpd-mount
    emptyDir: {}
    hostPath:
     path: /var/log
     type: Directory