--- 
apiVersion: batch/v1
kind: Job
metadata:
 name: job
 labels:
  env: dev
  team: devops
spec:
 template:
  metadata:
   name: job-on-alpine
   labels:
    name: demo-job
  spec:
   containers:
    - name: alpine
      image: alpine:latest
      args:
       - /bin/sh
       - -c
       - sleep 2m
   restartPolicy: OnFailure