--- 
apiVersion: batch/v1
kind: Job
metadata:
 name: job
 labels:
  env: dev
  team: devops
spec:
 selector:
  matchLabels:
   name: pod-job
 template:
  metadata:
   name: job-on-alpine
   labels:
    name: pod-job
  spec:
   containers:
    - name: alpine
      image: alpine:latest
      args:
       - /bin/sh
         -c
         sleep 2m
   restartPolicy: OnFailure