---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: nginx-rs
 labels:
  app: nginx
spec: 
 minReadySeconds: 2
 replicas: 2
 selector: 
  matchLabels: 
   app: nginx
 template: 
  metadata: 
   name: nginx-pod
   labels:
    app: nginx
    env: learning
  spec: 
   containers:
    - name: nginx-container
      image: nginx
      ports: 
       - containerPort: 8080
         protocol: TCP
       
---
apiVersion: v1
kind: Service
metadata: 
 name: nginx-service
spec:
 type: NodePort
 selector:
  app: nginx
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32567