---
apiVersion: v1
kind: Pod
metadata: 
 name: cmd-liveness-probe-no-restart-pod
 labels:
  app: alpine
  env: learning
spec: 
 restartPolicy: Never
 containers:
  - name: cmd-liveness-probe-no-restart-container
    image: alpine
    args:
     - /bin/sh
     - -c
     - touch /tmp/ready; sleep 2s; rm /tmp/ready; sleep 10s;
    livenessProbe: 
     exec: 
      command: 
       - cat
       - /tmp/ready
     initialDelaySeconds: 2
     periodSeconds: 10
     successThreshold: 1
     failureThreshold: 1