---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-http-livenessprobe-with-no-restart
 labels:
  app: httpd
  env: learning
spec:
 restartPolicy: Never
 containers: 
  - name: httpd-http-livenessprobe-no-restart-demo
    image: httpd
    ports:
     - containerPort: 80
       protocol: TCP
    livenessProbe:
     initialDelaySeconds: 5
     periodSeconds: 5
     successThreshold: 1
     failureThreshold: 1
     httpGet: 
      path: /
      port: 80