--- 
apiVersion: v1
kind: Pod
metadata: 
  name: "pod-resources-with-limits"
spec: 
  containers: 
    - 
      image: httpd
      name: "httpd-container"
      ports: 
        - 
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          memory: "512M"
          cpu: "1"
        requests:
          memory: "64M"
          cpu: "0.5"