---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-with-secret
spec:
 containers:
  - name: alpine
    image: alpine
    args:
     - /bin/sh
     - -c
     - sleep 1d
    envFrom:
     - secretRef:
        name: learning-secret