--- 
apiVersion: v1
kind: Pod
metadata: 
  name: "pod-liveness-probe"
spec: 
  restartPolicy: Never
  containers: 
    - 
      image: ubuntu:latest
      name: "ubuntu-container"
      command:
        - /bin/bash
        - -ec
        - touch /tmp/ready; sleep 10; rm /tmp/ready; sleep 20;
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        initialDelaySeconds: 5
        periodSeconds : 5