--- 
apiVersion: v1
kind: Pod
metadata: 
  name: "pod-liveness-probe"
spec: 
  restartPolicy: Always
  containers: 
    - 
      image: httpd:latest
      name: "http-container"
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 1