--- 
apiVersion: v1
kind: Service
metadata:
 name: httpd-service
 labels:
  app: httpd
  team: devops
spec:
 type: NodePort
 selector:
  app: httpd
 ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32555