---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-with-pv
spec:
 containers: 
  - name: alpine-container-with-pv
    image: alpine
    args:
     - /bin/sh
     - -c
     - sleep 1d
    volumeMounts:
     - mountPath: /tmp/logs
       name: logs-volume
 volumes:
  - name: logs-volume
    persistentVolumeClaim:
     claimName: learning-pvc