---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
 name: learning-pvc
spec:
 accessModes:
  - ReadWriteOnce
 selector:
  matchLabels:
   vol: pv
 resources:
  requests:
   storage: 1Gi
 volumeMode: Filesystem
 volumeName: learning-pv