--- 
apiVersion: v1
kind: PersistentVolume
metadata:
 name: httpd-pv
spec:
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /var/log
 volumeMode: Filesystem
 persistentVolumeReclaimPolicy: Retain
 capacity:
  storage: 1GiB