--- 
apiVersion: v1
kind: Pod
metadata:
 name: httpd-pod-with-persistent-volume
 labels:
  app: httpd
  team: devops
spec:
 containers:
  - name: httpd-container
    image: httpd:latest
    ports:
     - containerPort: 80
       protocol: TCP
    volumeMounts:
     - mountPath: /var/log
       name: pv-storage
 volumes:
  - persistentVolumeClaim:
     claimName: httpd-pvc
    name: pv-storage