--- 
apiVersion: v1
kind: Pod
metadata:
 name: httpd-pod
 labels:
  env: dev
  team: devops
  name: httpd-label
spec:
 containers:
  - name: httpd-container
    image: httpd:latest
    ports:
     - containerPort: 80
       protocol: TCP