--- 
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  env: test
  team: devops
  name: nginx-label
spec:
 containers:
  name: nginx-container
  image: nginx:latest
  ports:
   - containerPort: 8080
     protocol: TCP