--- 
apiVersion: v1
kind: Pod
metadata: 
  name: "Pod namespace"
  namespace: dev
spec: 
  containers: 
    - 
      image: httpd
      name: "httpd container"
      ports: 
        - 
          containerPort: 80
          protocol: TCP